services:
  code-indexing:
    image: qdrant/qdrant:latest
    container_name: code-indexing
    restart: unless-stopped
    ports:
      - "7333:6333"     # Host 7333 → container HTTP API (default 6333)
      - "7334:6334"     # Host 7334 → container gRPC API (default 6334)
    volumes:
      - ./storage:/qdrant/storage   # Host folder for vector segments
      - ./db:/qdrant/db             # Host folder for internal DB files
    # Using defaults, so no environment variables needed for ports or paths
    mem_limit: 12g
