name: qdrant-db

services:
  qdrant-db:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant-db
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"     # HTTP API
      - "${QDRANT_GRPC_PORT:-6334}:6334"     # gRPC API
    networks:
      - qdrant-network
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-db:/qdrant/db
    mem_limit: ${QDRANT_MEMORY_LIMIT:-2g}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "environment=${ENVIRONMENT:-dev}"
      - "service.type=database"
      - "service.name=qdrant"
      - "database.type=vector"
      - "database.engine=qdrant"
      - "database.use-case=similarity-search,embeddings"
      - "api.protocols=http,grpc"
      - "container.group=databases"
      - "monitoring.enabled=true"

volumes:
  qdrant-storage:
  qdrant-db:

networks:
  qdrant-network:
    name: qdrant-network
    driver: bridge