name: qdrant-db

services:
  qdrant-db:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant-db
    ports:
      - "${QDRANT_HTTP_PORT:-8633}:6333"     # HTTP API
      - "${QDRANT_GRPC_PORT:-8634}:6334"     # gRPC API
    networks:
      - qdrant-network
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-db:/qdrant/db
    mem_limit: ${QDRANT_MEMORY_LIMIT:-2g}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.docker.compose.project=${COMPOSE_PROJECT_NAME:-qdrant-db}"
      - "environment=${ENVIRONMENT:-dev}"
      - "service.type=database"
      - "service.name=qdrant"
      - "service.version=latest"
      - "database.type=vector"
      - "database.engine=qdrant"
      - "database.use-case=similarity-search,embeddings"
      - "api.protocols=http,grpc"
      - "backup.frequency=daily"
      - "backup.priority=high"
      - "monitoring.enabled=true"
      - "team.owner=${TEAM:-platform}"
      - "expose.ports=7333,7334"

volumes:
  qdrant-storage:
  qdrant-db:

networks:
  qdrant-network:
    name: qdrant-network
    driver: bridge