name: pickleizer-grafana

networks:
  pickleizer-test-network:
    name: pickleizer-test-network
    driver: bridge
  pickleizer-sim-network:
    name: pickleizer-sim-network
    driver: bridge
  pickleizer-dev-network:
    name: pickleizer-dev-network
    driver: bridge
  pickleizer-prod-network:
    name: pickleizer-prod-network
    driver: bridge
  pickleizer-monitoring-network:
    name: pickleizer-monitoring-network
    driver: bridge

services:
  loki:
    image: grafana/loki:latest
    container_name: pickleizer-loki
    ports:
      - "9710:3100"
    networks:
      - pickleizer-monitoring-network
      - pickleizer-test-network
      - pickleizer-sim-network
      - pickleizer-dev-network
      - pickleizer-prod-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  promtail:
    image: grafana/promtail:latest
    container_name: pickleizer-promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pickleizer-monitoring-network
      - pickleizer-test-network
      - pickleizer-sim-network
      - pickleizer-dev-network
      - pickleizer-prod-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9080/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana:latest
    container_name: pickleizer-grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        mkdir -p /etc/grafana/provisioning/dashboards
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        cat <<EOF > /etc/grafana/provisioning/dashboards/dashboards.yaml
        apiVersion: 1
        providers:
        - name: 'Pickleizer Dashboards'
          orgId: 1
          folder: 'Pickleizer'
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards
        EOF
        /run.sh
    ports:
      - "9700:3000"
    networks:
      - pickleizer-monitoring-network
      - pickleizer-test-network
      - pickleizer-sim-network
      - pickleizer-dev-network
      - pickleizer-prod-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
