name: memgraph-db

services:
  memgraph-db:
    image: memgraph/memgraph-mage:latest
    restart: unless-stopped
    container_name: memgraph-db
    ports:
      - "${MEMGRAPH_LOG_PORT:-7444}:7444"  # Log streaming/HTTP API
      - "${MEMGRAPH_BOLT_PORT:-7587}:7687"  # Bolt protocol
    networks:
      - memgraph-network
    volumes:
      - memgraph-db-data:/var/lib/memgraph
      - memgraph-db-logs:/var/log/memgraph
      - memgraph-db-conf:/etc/memgraph
    environment:
      - MEMGRAPH_USER=${MEMGRAPH_USER:-memgraph}
      - MEMGRAPH_PASSWORD=${MEMGRAPH_PASSWORD:-changeme}
    mem_limit: ${MEMGRAPH_MEMORY_LIMIT:-1g}
    command: ["--log-level=DEBUG"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole --username=${MEMGRAPH_USER} --password=${MEMGRAPH_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "environment=${ENVIRONMENT:-dev}"
      - "service_type=database"
      - "service_name=memgraph"
      - "database_type=graph"
      - "database_engine=memgraph"
      - "container_group=databases"
      - "monitoring_enabled=true"

  memgraph-lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "${MEMGRAPH_LAB_PORT:-7300}:3000"
    networks:
      - memgraph-network
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph-db
      - QUICK_CONNECT_MG_PORT=7687
    depends_on:
      - memgraph-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "environment=${ENVIRONMENT:-dev}"
      - "service_type=ui"
      - "service_name=memgraph-lab"
      - "ui_for=memgraph"
      - "ui_type=web"
      - "container_group=admin-tools"
      - "monitoring_enabled=true"

volumes:
  memgraph-db-data:
  memgraph-db-logs:
  memgraph-db-conf:

networks:
  memgraph-network:
    name: memgraph-network
    driver: bridge
  