name: pickleizer-memgraph-dev

services:
  pickleizer-memgraph-dev:
    image: memgraph/memgraph-mage:latest
    restart: unless-stopped
    container_name: pickleizer-memgraph-dev
    ports:
      - "8244:7444"  # Log streaming/HTTP API
      - "8287:7687"  # Bolt protocol
    networks:
      - pickleizer-dev-network
    volumes:
      - pickleizer-memgraph-dev-data:/var/lib/memgraph
      - pickleizer-memgraph-dev-logs:/var/log/memgraph
      - pickleizer-memgraph-dev-conf:/etc/memgraph
    environment:
      - MEMGRAPH_USER=${MEMGRAPH_USER}
      - MEMGRAPH_PASSWORD=${MEMGRAPH_PASSWORD}
    mem_limit: 8g
    command: ["--log-level=DEBUG"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole --username=${MEMGRAPH_USER} --password=${MEMGRAPH_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  pickleizer-memgraph-lab-dev:
    image: memgraph/lab:latest
    container_name: pickleizer-memgraph-lab-dev
    ports:
      - "8250:3000"  # Following 8xxx pattern
    networks:
      - pickleizer-dev-network
    environment:
      - QUICK_CONNECT_MG_HOST=pickleizer-memgraph-dev
      - QUICK_CONNECT_MG_PORT=7687
    depends_on:
      - pickleizer-memgraph-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pickleizer-memgraph-dev-data:
  pickleizer-memgraph-dev-logs:
  pickleizer-memgraph-dev-conf:

networks:
  pickleizer-dev-network:
    name: pickleizer-dev-network
    external: true